name: anchor-deploy-devnet

on:
  workflow_dispatch:
    inputs:
      cluster:
        description: "Solana cluster"
        required: true
        default: devnet
      program:
        description: "Program to deploy (anchor workspace member)"
        required: true
        default: trs_staking

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    env:
      ANCHOR_WALLET_JSON: ${{ secrets.ANCHOR_WALLET }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config libudev-dev libusb-1.0-0-dev build-essential bzip2 ca-certificates

      - name: Install Solana CLI (GitHub release fallback)
        run: |
          set -e
          SOLANA_VERSION="1.18.4"
          TARBALL_URL="https://github.com/solana-labs/solana/releases/download/v${SOLANA_VERSION}/solana-release-x86_64-unknown-linux-gnu.tar.bz2"
          echo "Downloading Solana ${SOLANA_VERSION} from ${TARBALL_URL}"
          for i in {1..6}; do
            if curl -fL --retry 3 --retry-delay 2 -o /tmp/solana.tar.bz2 "$TARBALL_URL"; then
              break
            fi
            echo "Download failed (attempt $i). Retrying in 5s..."
            sleep 5
          done
          mkdir -p "$HOME/.local/share/solana"
          tar -C "$HOME/.local/share/solana" -xjf /tmp/solana.tar.bz2
          ln -snf "$HOME/.local/share/solana/solana-release/bin" "$HOME/.local/share/solana/install/active_release/bin"
          echo "$HOME/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH
          "$HOME/.local/share/solana/install/active_release/bin/solana" --version
          ls -la "$HOME/.local/share/solana/install/active_release/bin"

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
          profile: minimal
          override: true

      - name: Install Anchor CLI
        run: |
          cargo install --git https://github.com/coral-xyz/anchor anchor-cli --locked

      - name: Configure wallet and RPC
        run: |
          set -e
          SOLANA_BIN_DIR="$HOME/.local/share/solana/install/active_release/bin"
          export PATH="$SOLANA_BIN_DIR:$PATH"
          which solana || true
          ls -la "$SOLANA_BIN_DIR" || true
          mkdir -p "$HOME/.config/solana"
          if [ -z "$ANCHOR_WALLET_JSON" ]; then echo "Missing secret ANCHOR_WALLET" && exit 1; fi
          echo "$ANCHOR_WALLET_JSON" > "$HOME/.config/solana/id.json"
          chmod 600 "$HOME/.config/solana/id.json"
          RPC_URL_INPUT=${{ secrets.SOLANA_RPC_URL }}
          if [ -z "$RPC_URL_INPUT" ]; then RPC_URL_INPUT="https://api.devnet.solana.com"; fi
          "$SOLANA_BIN_DIR/solana" config set --url "$RPC_URL_INPUT" --keypair "$HOME/.config/solana/id.json"
          "$SOLANA_BIN_DIR/solana-keygen" pubkey "$HOME/.config/solana/id.json"

      - name: Build workspace
        working-directory: toros-solana
        run: anchor build

      - name: Deploy program
        working-directory: toros-solana
        env:
          ANCHOR_WALLET: ${{ env.HOME }}/.config/solana/id.json
        run: anchor deploy -p "${{ github.event.inputs.program }}" --provider.cluster "${{ github.event.inputs.cluster }}"

      - name: Upload deploy artifacts
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: anchor-target
          path: toros-solana/target/deploy/**